farm_update.settings:
  type: config_object
  label: 'farmOS Update settings'
  mapping:
    exclude_config:
      type: sequence
      label: 'Configuration items excluded from automatic updates'
      sequence:
        type: string
        label: 'Configuration item'
