services:
  asset.inventory:
    class: Drupal\farm_inventory\AssetInventory
    arguments:
      [ '@entity_type.manager', '@datetime.time' ]
  farm_inventory.log_event_subscriber:
    class: Drupal\farm_inventory\EventSubscriber\LogEventSubscriber
    arguments:
      [ '@cache_tags.invalidator', '@datetime.time' ]
    tags:
      - { name: 'event_subscriber' }
