# Schema for flag config entity.
farm_flag.flag.*:
  type: config_entity
  label: 'Flag'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    entity_types:
      type: sequence
      label: 'Entity types'
      nullable: true
      sequence:
        type: sequence
        label: 'Entity type'
        sequence:
          type: string
          label: 'Bundle'
