# Schema for the configuration files of the farm_fieldkit module.
farm_fieldkit.field_module.*:
  type: config_entity
  label: 'Field module'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Type'
    description:
      type: text
      label: 'Description'
    library:
      type: string
      label: 'Library name'
