# Schema for actions.
action.configuration.asset_assign_action:
  type: action_configuration_default
  label: 'Configuration for the asset assign action'
action.configuration.log_assign_action:
  type: action_configuration_default
  label: 'Configuration for the log assign action'
